# Ejercicios Semana 4

# Ejercicio 1

Escribe un programa que pida al usuario ingresar una lista de números separados por comas. Luego, crea una tupla con esos números y muestra por pantalla la tupla creada y la suma de sus elementos.

## Ejercicio 2

Escribir un programa que pregunte al usuario su nombre, apellido, edad y teléfono, y que lo guarde en un diccionario. Después debe mostrar por pantalla el mensaje:  \<nombre apellido\> tiene \<edad\> años y su número de teléfono es \<telefono\>.

# Ejercicio 3

Escribir un programa que pregunte una fecha en formato dd/mm/aaaa y muestre por pantalla la misma fecha en formato dd de \<mes\> de aaaa donde \<mes \> es el nombre del mes. Para ello cree un diccionario que relacione el valor de mm con el nombre del mes.

# Ejercicio 4

Escribe un programa que pida al usuario que ingrese dos listas de números enteros separados por espacios. Luego, crea dos conjuntos con los elementos de cada lista y muestra por pantalla los siguientes conjuntos:

    1. La unión de los dos conjuntos
    2. La intersección de los dos conjuntos
    3. Los elementos que están en el primer conjunto pero no en el segundo
    4. Los elementos que están en el segundo conjunto pero no en el primero

# Ejercicio 5

Dadas las listas de nombres y edades:
nombre=[Juan, Ana, Marcela, Claudio, Nicolás, Cecilia, Tomas, Pedro]
edades=[25, 15, 13, 21, 45, 32, 17, 33]
1. Crear una lista de tuplas que contenga los nombres y las edades de las personas mayores de 18 años. Atención, usar la función `zip()`.
2. Ordenar la lista resultante de forma alfabética por el nombre de las personas.

#Ejercicio 6

Usando la herramienta de compresión de listas y diccionarios aprendidas en clases crear:

1. Crea una lista de los cuadrados de los números del 1 al 10 utilizando una comprensión de listas.
2. Crea una lista de los números pares del 1 al 20 utilizando una comprensión de listas.
3. Crea un diccionario que asocie ciudades con sus temperaturas actuales de las siguiente listas.
ciudades = ["Buenos Aires", "Madrid", "Roma", "París"]
temperaturas = [28, 16, 21, 19]

# Ejercicio 7

Escribe un programa que lea una lista de palabras separadas por espacios y cree una tupla con ellas. Luego, muestra por pantalla la tupla creada y la cantidad de veces que aparece la letra más repetida en todas las palabras.

# Ejercicio 8

Escribe un programa que cree una tupla de n elementos, donde n es un número ingresado por el usuario. Luego, pide al usuario que ingrese n tuplas de dos elementos cada una. El programa debe crear una nueva tupla que contenga la suma de los elementos de cada tupla ingresada. Por ejemplo, si el usuario ingresa las tuplas (1, 2) y (3, 4), el programa debe crear la tupla (4, 6).

# Ejercicio 9

Imagina que eres la/el gerente de una tienda en línea y estás revisando tu base de datos de clientes. Descubres que algunos clientes se han registrado varias veces con la misma información de contacto, pero diferentes nombres de usuario. La lista que tienes es: 

`clientes = [

  (1, "Ana", "García", "ana@example.com", "Calle Falsa 123"), 

  (2, "Pedro", "Martínez", "pedro@example.com", "Avenida Siempreviva 742"),

  (3, "Luisa", "Fernández", "luisa@example.com", "Calle Falsa 123"),

  (4, "Juan", "Pérez", "juan@example.com", "Calle Falsa 123"), 

  (5, "Ana", "García", "ana@example.com", "Calle Falsa 123")
  
  ]`

Para simplificar tu base de datos, decides eliminar los registros duplicados y ordenar la lista de clientes alfabéticamente. Escribe un código que haga esto.

# Ejercicio 10

Escribe un programa que le permita al usuario registrar información sobre estudiantes en una escuela. Cada estudiante tendrá un nombre y apellido, una edad y una lista de materias en las que está inscrito.
El programa deberá guardar toda la información guardada, y además deberá indicar cuantas y cuales son las materias a las que hay por lo menos un estudiante inscrito. 

Probá para las siguientes informaciones

- Nombre: Juan Perez,
  Edad: 18,
  Materias: Matemáticas, Física, Química
- Nombre: Ana Suarez, 
  Edad: 17,
  Materias: Lengua, Historia, Geografía
- Nombre: Pedro Martinez,
  Edad: 16,
  Materias: Inglés, Música
- Nombre: María Barbosa,
  Edad: 18,
  Materias: Matemáticas, Física, Dibujo
- Nombre: Luis Sanchez, 
  Edad: 17,
  Materias: Biología, Historia, Geografía